#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Standbykiller for NanoHome - sends OFF to topic if device falls below [W]
#/////////////////////////////////////////////////////////////////////////////////////

# Catch Parameters
device="$2"
maxpower="$3"
rootpath="INSTALLDIR"

# Device Support
if [ ! "$device" = "all" ]; then
	. $rootpath/dev_compatibility $device
fi

# Environment
service_line="standbykillersvc $device $maxpower"
devdesc="$(cat $rootpath/devlist | grep $device | cut -d: -f2 )"

# show devices
if [ "$1" = "show" ] && [ ! -z "$device" ]; then
	
	ms="$(grep "$service_line" $rootpath/driver/nanohome_helper)"
	
	# show active state of device
	if [ "$device" = "all" ] && [! -z "$ms"]; then
	
		ms="$(grep "$service_line" $rootpath/driver/nanohome_helper)"
		statusmsg "Standbykiller" "white" " aktiv" "#c0fcb1" "$ms" "hotpink"
	
	elif grep "$service_line" $rootpath/driver/nanohome_helper ; then
		
		statusmsg "Standbykiller" "white" " aktiv" "#c0fcb1" "$devdesc [$maxpower]" "hotpink"
		
	else

		statusmsg "Standbykiller" "white" " inaktiv" "grey" "Kein Standbykiller aktiv" "grey"

	fi



# add device
elif [ "$1" = "add" ] && [ ! -z "$device" ] && [ ! -z "$maxpower" ]; then
	
	if grep "$service_line" $rootpath/driver/nanohome_helper ; then
	
		statusmsg "Standbykiller" "white" "$devdesc" "hotpink" "Standbykiller exists" "white"
		exit 1
		
	else
	
		echo "$service_line" >> $rootpath/driver/nanohome_helper
		systemctl restart nanohome_helper
		statusmsg "Standbykiller" "white" " aktiviert" "#c0fcb1" "$devdesc [$maxpower]" "hotpink"

	fi

# remove device
elif [ "$1" = "remove" ] && [ ! -z "$device" ]; then

	sed -i "/$service_line/d" $rootpath/driver/nanohome_helper
	systemctl restart nanohome_helper
	statusmsg "Standbykiller" "white" " deaktiviert" "grey" "$devdesc" "hotpink"


else

	echo "----------------------------------------------------------"
	echo "Usage: standbykiller show|add|remove device (standbypower)"
	echo "----------------------------------------------------------"
	echo

	exit 1

fi
