#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# nanohome - measurements service
#
# Discover and get measurements from Shelly gen3 pm devices
# - Subscribe to the status topic of all devices
# - Filter not monitored components from messages
# - Write device status in Influx "Devices" bucket
# - For connected devices with valid deription
#   parse measurement values and write them into Influx bucket "Measurements"
#/////////////////////////////////////////////////////////////////////////////////////

# Convert string-boolean to 1 or 0
convert_value() {
	[[ "$1" == "true" ]] || [[ "$1" == "on" ]] && echo 1 || echo 0
}

# MQTT connection string with credentials
MQTT_CONNECTION_STRING=(
	-h "${MQTT_SERVER}"
	-u "${MQTT_USER}"
	-P "${MQTT_PASSWORD}"
)

# MQTT retained message subscription options
MQTT_RETAINED_OPTIONS=(
	--retained-only
	--nodelay
	--quiet
	-C 1
	-W 1
)

#===============================================================
# Infinitely subscribe to "+/status/+"
#===============================================================

mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" --nodelay --quiet -F "%j" -t "+/status/+" |
while read -r COMPONENTSTATUS; do

	# Extract payload and topic from json formatted message
	STATUSMESSAGE=$( jq -r '.payload' <<< "${COMPONENTSTATUS}" )
	STATUSTOPIC=$( jq -r '.topic' <<< "${COMPONENTSTATUS}" )
	DEVICEID=$( cut -d '/' -f 1 <<< "${STATUSTOPIC}" )
	COMPONENT=$( cut -d '/' -f 3 <<< "${STATUSTOPIC}" )
	ONLINEVALUE=1 # Assume getting a message equals device is online

	[[ $LOG_DEBUG ]] && echo -e "${LOG_INFO} Devicewatcher: Message recived - [${DEVICEID}/${COMPONENT}]" >> /proc/1/fd/1

	#===============================================================
	# Filter components not monitored
	#===============================================================

	[[ " ${NANOHOME_NOT_MONITORED_COMPONENTS//,/ } " =~ " ${COMPONENT} " ]] && continue

	#===============================================================
	# Filter components not connected
	#===============================================================

	CONNECTEDTOPIC="${DEVICEID}/status/${COMPONENT}/connected"

	CONNECTED=$(
		mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" \
		"${MQTT_RETAINED_OPTIONS[@]}" \
		-t "${CONNECTEDTOPIC}"
	)

	CONNECTEDVALUE=$( convert_value "${CONNECTED}" )

	if [[ $CONNECTEDVALUE -eq 0 ]]; then

		# Publish connected=false for newly discovered components, this will make them visible on the device manager dashboard
		mosquitto_pub -r "${MQTT_CONNECTION_STRING[@]}" -t "${CONNECTEDTOPIC}" -m "false"

		# Add device ping to influxdb "Devices" bucket
		DEVICE_PAYLOAD="${DEVICEID},Component=${COMPONENT} Online=${ONLINEVALUE},Connected=${CONNECTEDVALUE}"
		influx write -b "${INFLUX_BUCKET_DEVICES}" -p s "${DEVICE_PAYLOAD}"

		[[ $LOG_SERVICES ]] && echo -e "${LOG_INFO} Devicewatcher: Device ping saved - [${DEVICE_PAYLOAD}]" >> /proc/1/fd/1
		continue
	fi

	#===============================================================
	# Filter components without description
	#===============================================================

	DESCRIPTIONTOPIC="${DEVICEID}/status/${COMPONENT}/description"

	DESCRIPTION=$(
		mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" \
		"${MQTT_RETAINED_OPTIONS[@]}" \
		-t "${DESCRIPTIONTOPIC}"
	)

	if [[ -z "${DESCRIPTION}" ]]; then

		# Add device ping to influxdb "Devices" bucket
		DEVICE_PAYLOAD="${DEVICEID},Component=${COMPONENT} Online=${ONLINEVALUE},Connected=${CONNECTEDVALUE}"
		influx write -b "${INFLUX_BUCKET_DEVICES}" -p s "${DEVICE_PAYLOAD}"

		[[ $LOG_SERVICES ]] && echo -e "${LOG_INFO} Devicewatcher: Device ping saved - [${DEVICE_PAYLOAD}]" >> /proc/1/fd/1
		continue
	fi

	DESCRIPTION_ESCAPED="${DESCRIPTION// /\\ }"

	#===============================================================
	# Process measurement payload
	#===============================================================

	POWER=$( jq -r '.apower' <<< "${STATUSMESSAGE}" )
	OUTPUT=$( jq -r '.output' <<< "${STATUSMESSAGE}" )
	ENERGY=$(jq -r '.aenergy.total' <<< "${STATUSMESSAGE}" )
	VOLTAGE=$( jq -r '.voltage' <<< "${STATUSMESSAGE}" )
	CURRENT=$( jq -r '.current' <<< "${STATUSMESSAGE}" )
	DEVICETEMP=$( jq -r '.temperature.tC' <<< "${STATUSMESSAGE}" )
	CURRENTPOSITION=$( jq -r '.current_pos' <<< "${STATUSMESSAGE}" )
	ROOM_TEMP=$( jq -r '.tC' <<< "${STATUSMESSAGE}" )
	ROOM_HUM=$( jq -r '.rh' <<< "${STATUSMESSAGE}" )
	BATTERY=$( jq -r '.battery.percent' <<< "${STATUSMESSAGE}" )

	#===============================================================
	# Publish output value
	#===============================================================

	# This value will be used on the home dashboard
	if [[ "${CURRENTPOSITION}" != "null" ]]; then
		OUTPUTVALUE="${CURRENTPOSITION}"
	else
		OUTPUTVALUE=$( convert_value "${OUTPUT}" )
	fi

	OUTPUTTOPIC="${DEVICEID}/status/${COMPONENT}/output"

	mosquitto_pub -r "${MQTT_CONNECTION_STRING[@]}" \
		-t "${OUTPUTTOPIC}" -m "${OUTPUTVALUE}"

	#===============================================================
	# Write measurements into influx buckets
	#===============================================================

	# InfluxDB: Write a device ping into the 'Devices' bucket
	DEVICE_PAYLOAD="${DEVICEID},Component=${COMPONENT},Description=${DESCRIPTION_ESCAPED} Online=${ONLINEVALUE},Connected=${CONNECTEDVALUE},Output=${OUTPUTVALUE}"
	influx write -b "${INFLUX_BUCKET_DEVICES}" -p s "${DEVICE_PAYLOAD}"

	[[ $LOG_SERVICES ]] && echo -e "${LOG_INFO} Devicewatcher: Device ping saved - [${DEVICE_PAYLOAD}]" >> /proc/1/fd/1

	# Prepare a measurement string for the Influx CLI (line protocol)
	MEASUREMENT_PAYLOAD="${DESCRIPTION_ESCAPED} "

	[[ "${POWER}" != "null" ]] && MEASUREMENT_PAYLOAD+="Power=${POWER},"
	[[ "${ENERGY}" != "null" ]] && MEASUREMENT_PAYLOAD+="Energy=${ENERGY},"
	[[ "${VOLTAGE}" != "null" ]] && MEASUREMENT_PAYLOAD+="Voltage=${VOLTAGE},"
	[[ "${CURRENT}" != "null" ]] && MEASUREMENT_PAYLOAD+="Current=${CURRENT},"
	[[ "${DEVICETEMP}" != "null" ]] && MEASUREMENT_PAYLOAD+="DeviceTemp=${DEVICETEMP},"
	[[ "${ROOM_TEMP}" != "null" ]] && MEASUREMENT_PAYLOAD+="Temperature=${ROOM_TEMP},"
	[[ "${ROOM_HUM}" != "null" ]] && MEASUREMENT_PAYLOAD+="Humidity=${ROOM_HUM},"
	[[ "${BATTERY}" != "null" ]] && MEASUREMENT_PAYLOAD+="Battery=${BATTERY},"

	# InfluxDB: Write measurements into the 'Measurements' bucket
	if [[ "${MEASUREMENT_PAYLOAD}" != "${DESCRIPTION_ESCAPED} " ]]; then
		MEASUREMENT_PAYLOAD="${MEASUREMENT_PAYLOAD%,}"

		influx write -b "${INFLUX_BUCKET_MEASUREMENTS}" -p s "${MEASUREMENT_PAYLOAD}"

		[[ $LOG_SERVICES ]] && echo -e "${LOG_INFO} Devicewatcher: Measurement saved - [${MEASUREMENT_PAYLOAD}]" >> /proc/1/fd/1
	else
		[[ $LOG_DEBUG ]] && echo -e "${LOG_WARN} Devicewatcher: No measurement - [${DEVICEID}/${COMPONENT}]" >> /proc/1/fd/1
	fi
done
