#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Nanohome MQTT Shell
#
# Execute allowed shell commands published to the defined command input topic
#/////////////////////////////////////////////////////////////////////////////////////

# Configuration
FIFO_FILE=".mqtt_shell.cache"
ALLOWED_COMMANDS=(${NANOHOME_SHELL_ALLOWED_COMMANDS//,/ }) # Convert comma-separated list to array

# Cleanup function
cleanup() {
    echo "Cleaning up..."
    rm -f "$FIFO_FILE"
    exit 0
}

# Ensure FIFO exists
[ ! -p "$FIFO_FILE" ] && mkfifo "$FIFO_FILE"

# Trap to clean up on exit
trap cleanup EXIT

# Start MQTT subscription
mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" -t "${MQTT_TOPIC_CMDINPUT}" > "$FIFO_FILE" &

# Main loop
while read -r line <"$FIFO_FILE"; do
    COMMAND=$(echo "$line" | awk '{print $1}')
    
    # Check if command is allowed
    for ALLOWED in "${ALLOWED_COMMANDS[@]}"; do
        if [[ "$ALLOWED" == "$COMMAND" ]]; then
            # Execute the command and publish output
			OUTPUT=$(bash -c "$line" 2>&1)

            mosquitto_pub "${MQTT_CONNECTION_STRING[@]}" -t "${MQTT_TOPIC_CMDOUTPUT}" -m "$OUTPUT"
            break
        fi
    done
done

