#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Nanohome MQTT Shell
#
# Execute allowed shell commands published to the defined command input topic
#/////////////////////////////////////////////////////////////////////////////////////

# Advanced Settings
touch .mqtt_shell.pid
touch .mqtt_shell.cmds
touch .mqtt_shell.out
clean=".mqtt_shell.cmds .mqtt_shell.pid .mqtt_shell.out"
p=".mqtt_shell.cache"
pid=$(cat .mqtt_shell.pid)

# Clean
ctrl_c() {
  echo "Cleaning up..."
  rm -f $p;rm $clean;kill $pid 2>/dev/null
  if [[ "$?" -eq "0" ]];
  then
     echo "Exit success";exit 0
  else
     exit 1
  fi
}

# MQTT Listen on topic_cmdInput
listen(){
	([ ! -p "$p" ]) && mkfifo $p
	(mosquitto_sub -h "${MQTT_SERVER}" -u "${MQTT_USER}" -P "${MQTT_PASSWORD}" -t "${TOPIC_CMDINPUT}" > $p 2>/dev/null) &
	echo "$!" > .mqtt_shell.pid
	while read line <$p; do
	
		# Only execute allowed commands
		IFS=',' read -r -a ALLOWEDCOMMANDS <<< "${SHELL_ALLOWED_COMMANDS}"
		COMMAND=$(echo "$line" | awk '{print $1;}')
		
		for item in "${ALLOWEDCOMMANDS[@]}"; do
			if [ "$item" == "$COMMAND" ]; then
				echo $line > .mqtt_shell.cmds
				(bash .mqtt_shell.cmds | tee .mqtt_shell.out) && mosquitto_pub -h "${MQTT_SERVER}" -u "${MQTT_USER}" -P "${MQTT_PASSWORD}" -t "${TOPIC_CMDOUTPUT}" -f .mqtt_shell.out;>.mqtt_shell.out
			fi
		done
	done
}

usage(){
	echo "    MQTT_shell - Drop bash commands"
	echo "  Usage: $0 -s [Change Settings inside]"
	echo "  Subscripe to topic /"${TOPIC_CMDOUTPUT}", publish to topic /"${TOPIC_CMDINPUT}""
}


case "$1" in
-s |--start)
trap ctrl_c INT
listen
;;
*)
usage
exit 1
;;
esac

