#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Nanohome MQTT Shell
#
# Execute allowed shell commands published to the defined command input topic
#/////////////////////////////////////////////////////////////////////////////////////

# TODO: Test
MQTT_CONNECTION_STRING=(
	-h "${MQTT_SERVER}"
	-u "${MQTT_USER}"
	-P "${MQTT_PASSWORD}"
)

# Configuration
FIFO_FILE=".mqtt_shell.cache"
ALLOWED_COMMANDS=(${NANOHOME_SHELL_ALLOWED_COMMANDS//,/ })

# Ensure FIFO exists
rm -f "${FIFO_FILE}" && mkfifo "${FIFO_FILE}"

# Start MQTT subscription
mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" -t "${MQTT_TOPIC_CMDINPUT}" > "${FIFO_FILE}" &

# Main loop
while read -r COMMANDLINE <"${FIFO_FILE}"; do
    COMMAND=$(echo "${COMMANDLINE}" | awk '{print $1}')
    
    # if command is allowed, execute it and publish result 
    for ALLOWED in "${ALLOWED_COMMANDS[@]}"; do
        if [[ "${ALLOWED}" == "${COMMAND}" ]]; then
			OUTPUT=$(bash -c "${COMMANDLINE}" 2>&1)
            mosquitto_pub "${MQTT_CONNECTION_STRING[@]}" -t "${MQTT_TOPIC_CMDOUTPUT}" -m "${OUTPUT}"
            break
        fi
    done
done

