#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# nanohome - mqtt shell service
#
# Execute allowed shell command
# - Subscribe to "nanohome/shell/input"
# - Execute the command if allowed
# - Publish the result to "nanohome/shell/output"
#/////////////////////////////////////////////////////////////////////////////////////

# MQTT connection string with credentials
MQTT_CONNECTION_STRING=(
	-h "${MQTT_SERVER}"
	-u "${MQTT_USER}"
	-P "${MQTT_PASSWORD}"
)

# Define allowed bash commands
ALLOWED_COMMANDS=(${NANOHOME_SHELL_ALLOWED_COMMANDS//,/ })
FIFO_FILE=".nanohome_shell.cache"

# Ensure FIFO exists
rm -f "${FIFO_FILE}" && mkfifo "${FIFO_FILE}"

# Start MQTT subscription
mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" -t "${MQTT_TOPIC_CMDINPUT}" > "${FIFO_FILE}" &

# If recived command is allowed, execute it and publish result
while read -r COMMANDLINE <"${FIFO_FILE}"; do
    COMMAND=${COMMANDLINE%% *}

    if [[ " ${ALLOWED_COMMANDS[*]} " == *" ${COMMAND} "* ]]; then
        OUTPUT=$(bash -c "${COMMANDLINE}" 2>&1)
        [[ -n "${OUTPUT}" ]] && RESULT=$OUTPUT || RESULT="command executed"
        mosquitto_pub "${MQTT_CONNECTION_STRING[@]}" -t "${MQTT_TOPIC_CMDOUTPUT}" -m "${RESULT}"
    fi
done
