#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# nanohome - standbymanager service
#
# Turn off output if power goes below threshold
# - Subscribe to the components status topic
# - Extract current output power from every message
# - Check if power is below threshold 
# - Turn off output if so
#/////////////////////////////////////////////////////////////////////////////////////

JSONCONFIG=$1

# Extract payload and device details from json formatted message
DEVICEID=$( jq -r '.deviceId' <<< "${JSONCONFIG}" )
COMPONENT=$( jq -r '.component' <<< "${JSONCONFIG}" )
DESCRIPTION=$( jq -r '.description' <<< "${JSONCONFIG}" )
THRESHOLD=$( jq -r .threshold <<< "${JSONCONFIG}" )
STANDBYWAIT=$( jq -r .wait <<< "${JSONCONFIG}" )

[[ "${STANDBYWAIT}" == "null" ]] && STANDBYWAIT=1

STATUSTOPIC="${DEVICEID}/status/${COMPONENT}"
STANDBYTOPIC="nanohome/standby/${DESCRIPTION}"
CONTROLTOPIC="${DEVICEID}/command/${COMPONENT}"

# Get last published standby state
get_last_state() {

	local JSONCONFIG=$(
		mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" \
		"${MQTT_RETAINED_OPTIONS[@]}" \
		-t "${STANDBYTOPIC}"
	)

	local state=$( jq -r .state <<< "${JSONCONFIG}" )
	return "${state}"
}

#===============================================================
# Infinitely subscribe to devices status topic
#===============================================================

mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" -t "${STATUSTOPIC}" |
while read -r COMPONENTSTATUS; do
	# Extract current power from json formatted message
	CURRENTPOWER=$( jq -r .apower <<< "${COMPONENTSTATUS}" )

	# Get last standby state
	LAST_STATE=$( get_last_state )

	# Manage standby - don't kill the device if it just started
	if awk 'BEGIN { exit !('$CURRENTPOWER' == 0) }'; then

		NEW_STATE="off"
		LOGMESSAGE="Off, nothing to do"
	
	elif awk 'BEGIN { exit !('$CURRENTPOWER' < '$THRESHOLD') }'; then
		case "${LAST_STATE}" in
			"off")
				NEW_STATE="on"
				LOGMESSAGE="Just started"
				sleep $STANDBYWAIT
				;;
			"on")
				NEW_STATE="off"
				LOGMESSAGE="Below threshold - turning off"
				mosquitto_pub "${MQTT_CONNECTION_STRING[@]}" -t "${CONTROLTOPIC}" -m "off"
				;;
			*)
				NEW_STATE="off"
				LOGMESSAGE="Something happened that shouldn't"
				;;
		esac
	elif awk 'BEGIN { exit !('$CURRENTPOWER' > '$THRESHOLD') }'; then
		case "${LAST_STATE}" in
			"off")
				NEW_STATE="on"
				LOGMESSAGE="Just started"
				sleep $STANDBYWAIT
				;;
			"on")
				NEW_STATE="on"
				LOGMESSAGE="On - nothing to do"
				;;
			*)
				NEW_STATE="off"
				LOGMESSAGE="Something happened that shouldn't"
				;;
		esac
	fi

	# Update the json with a new state and publish it
	if [[ "${NEW_STATE}" != "${LAST_STATE}" ]]
				
		JSONCONFIG_UPDATED=$(
			jq --arg state "${NEW_STATE}" '.state = "$state"' <<< "${JSONCONFIG}"
		)

		mosquitto_pub -r "${MQTT_CONNECTION_STRING[@]}" \
		-t "${STANDBYTOPIC}" -m "${JSONCONFIG_UPDATED}"
	fi

	# Log
	[[ $LOG_SERVICE ]] && echo -e "${LOG_INFO} Standbywatcher: ${DESCRIPTION} - ${LOGMESSAGE}"
done