#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# nanohome - standbywatcher service
#
# Enable or disable a standbymanager for a device
# if there is a new retained message in "nanohome/standby/+"
#/////////////////////////////////////////////////////////////////////////////////////

# MQTT connection string with credentials
MQTT_CONNECTION_STRING=(
	-h "${MQTT_SERVER}"
	-u "${MQTT_USER}"
	-P "${MQTT_PASSWORD}"
)

# MQTT retained message subscription options
MQTT_RETAINED_OPTIONS=(
	--retained-only
	--nodelay
	--quiet
	-C 1
	-W 1
)

# Service Topic:
SERVICETOPIC="nanohome/standby/+"

# Temporary storage for active services
STATE_FILE="/tmp/standbywatcher.state"
touch "$STATE_FILE"

#===============================================================
# Functions
#===============================================================

# Start a background service
start_standbyservice() {
    local msg="$1"
    local id=$( echo -n "$msg" | md5sum | cut -d ' ' -f1 )
	local description=$( jq -r '.description' <<< "${msg}" )

    # Check if service is already running
    if grep -q "$id" "$STATE_FILE"; then
		[[ $LOG_DEBUG ]] && echo -e "${LOG_INFO} Standbywatcher: standbymanager for [$description] already running" >> /proc/1/fd/1
    else
        [[ $LOG_SERVICE ]] && echo -e "${LOG_SUCC} Standbywatcher: starting new standbymanager for [$description]" >> /proc/1/fd/1
        nohup /bin/bash "${NANOHOME_ROOTPATH}/services/standbymanager" "$msg" > "/tmp/standbymanager_$id.log" 2>&1
    fi
}

# Stop a background service
stop_standbyservice() {
    local msg="$1"
    local id=$( echo -n "$msg" | md5sum | cut -d ' ' -f1 )
    local description=$( jq -r '.description' <<< "${msg}" )

    if grep -q "$id" "$STATE_FILE"; then
		[[ $LOG_SERVICE ]] && echo -e "${LOG_SUCC} Standbywatcher: disabling standbymanager for [$description]" >> /proc/1/fd/1

        local pid=$( grep "$id" "$STATE_FILE" | awk '{print $2}' )
        kill "$pid"
        sed -i "/$id/d" "$STATE_FILE"
    fi
}

#===============================================================
# Infinitely subscribe to "nanohome/standby/+"
#===============================================================

# Start a standbymanager if a new config gets published

mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" -t "${SERVICETOPIC}" -R |
while read -r MESSAGE; do
    if [[ -n "${MESSAGE}" ]]; then
        start_standbyservice "${MESSAGE}"
    fi
done &

mosquitto_sub "${MQTT_CONNECTION_STRING[@]}" -t "${SERVICETOPIC}" --retained-only |
while read -r MESSAGE; do
    if [[ -z "${MESSAGE}" ]]; then
        stop_standbyservice "${MESSAGE}"
    fi
done &
