#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Put CPU Temperature into InfluxDB
#/////////////////////////////////////////////////////////////////////////////////////

# Load config
. INSTALLDIR/config.cfg

# Environment
Topic="Temperature"
Sensor="NanoHome_CPU"

# Read Sensor
cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp)
cpuTemp1=$(($cpuTemp0/1000))
cpuTemp2=$(($cpuTemp0/100))
cpuTempM=$(($cpuTemp2 % $cpuTemp1))
CPU=$cpuTemp1"."$cpuTempM

# Send to InfluxDB
curl -i -XPOST 'http://'$influxdb_server':8086/write?db='$influxdb_database --data-binary $Topic' '$Sensor'='$CPU
