#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Put Disk Space into InfluxDB
#/////////////////////////////////////////////////////////////////////////////////////

# Load config
. INSTALLDIR/config.cfg

# Environment
Topic="Diskspace_Free"
Sensor="NanoHome_Disk"

# Get Disk Space
disk=$(df -m /dev/sda1 | tail -1 | awk '{print $4}')

# Send to InfluxDB
curl -i -XPOST 'http://'$influxdb_server':8086/write?db='$influxdb_database --data-binary $Topic' '$Sensor'='$disk
